//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popup.Dictionairy.OData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> CorrectAnswer { get; set; }
        public Nullable<System.DateTime> LastCorrectAnswered { get; set; }
        public Nullable<int> CourseId { get; set; }
    
        public virtual Courses Course { get; set; }
    }
}
